#Version: 0.1
FROM ubuntu:14.04
MAINTAINER Robin Wang "robin.w.wang@ericsson.com"
RUN apt-get update
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 627220E7
RUN echo 'deb http://archive.scrapy.org/ubuntu scrapy main' > /etc/apt/sources.list.d/scrapy.list
RUN sudo apt-get update && sudo apt-get -y install scrapy-0.25

